#####COMMON API PROPERTIES FOR ALL ENVIRONMENT#####
#api_baseUrl = https://apirest.wyscout.com
#api_username = px5bl1m-6b8hmectw-lcke5dk-7u13bb23ef
#api_password = sj.=&eL?6fS2^fYeZkLSDpz*u8axNI
##Area Properties
#areaTable_jsonObjectName=areas
#areaTable_endPoint=/v3/areas
##Area Properties
#competition_jsonObjectName=areas
#areaTable_sqlQuery=SHOW COLUMNS FROM raw.alain_wyscout.area
##Season Table Properties
#seasonTable_jsonObjectName=areas
#seasonTable_endPoint=/v3/competitions/384/seasons
#seasonTable_sqlQuery=SHOW COLUMNS FROM raw.alain_wyscout.season
#areaList = ALB, ARE, ARG, AUS, AUT, AZE, BGR, BIH, BLR, BOL, BRA, CHE, CHL, CHN, CRI, CYP, CZE, DEU, DNK, DZA, ECU, ESP, FIN, FRA, GEO, GRC, GTM, HND, HRV, HUN, IRL, IRN, ISL, ISR, ITA, JPN, KAZ, KOR, MAR, MEX, MKD, NLD, NOR, PAN, PER, POL, PRT, PRY, ROU, RUS, SAU, SRB, SVK, SVN, SWE, TUN, TUR, URY, USA, VEN, XEN, XSC
#competitionIdList = 127, 129, 139, 142, 143, 146, 152, 168, 177, 189, 209, 213, 255, 256, 257, 258, 263, 283, 284, 287, 301, 302, 310, 323, 328, 335, 339, 340, 346, 358, 364, 400, 412, 413, 414, 422, 423, 425, 426, 448, 451, 457, 465, 480, 495, 503, 506, 508, 520, 524, 527, 534, 546, 551, 591, 615, 617, 626, 635, 669, 682, 684, 685, 688, 692, 694, 705, 707, 719, 723, 729, 741, 750, 775, 776, 795, 796, 797, 808, 823, 830, 841, 843, 844, 852, 867, 869, 879, 880, 886, 905, 1493, 43172
#
#
##TEAM ADVANCE STATS
#teamAdvanceCompetitionIDList=146, 255, 323, 364, 426, 448, 524, 534, 551, 626, 635, 707, 729, 741, 795, 852, 867, 869, 879
#teamAdvanceCompetitionIDSize=1
#teamAdvanceTeamIdSize=all
#
##Pass 'all' or any number like'4' or '5'... '100'
#seasonIDSize=4
#competitionIdSize=3
##teamIdSize=3
#teamIdSize=all
#
######COMMON DB PROPERTIES FOR ALL ENVIRONMENT#####
##Raw
#catalogs_name = raw
#schemas_name=alain_wyscout
##Transform
#catalogs_tranformed = transformed
#schemas_tranformed=alain_wyscout
#
##TABLES NAME
##Raw
#area_tablename=area
#competition_tablename=competition
#season_tablename=season
#standings_tablename=standings
#teams_tablename=teams
#children_teams_tablename=children_teams
#squad_tablename=squad
#matches_tablename=matches
#team_advancestats_tablename=team_advancestats
#player_advancestats_tablename=player_advancestats
#match_advancestats_tablename=match_advancestats
##Transform
#players_overview_table=players_overview
#striker_scores_table=striker_scores
#compatibility_scores_table=compatibility_scores
#
#
#
#################################################################################
########################SAAL PROD DATA CONFIGURATION #############################
####TRINO PROPERTIES###
#trino_ui_host=https://trino-prod.digixt.ae
#env_host = trino-prod.digixt.ae
#env_port = 443
#env_username = admin
#env_password = Prod@2024
#env_BASE_URL_SERVICE = https://prod.digixt.ae
#catalog_name = raw
#user_name=admin
#user_password=admin
#env_BASE_URL_IDP = https://prod.digixt.ae
#env_Client_NAME = datalake-client
#env_Login_URL = /auth/realms/Datalake/protocol/openid-connect/token
#
#
#
############################################################################
#
#
########################ALAIN DEV DATA CONFIGURATION #############################
####TRINO PROPERTIES###
##trino_ui_host=https://trinodev.alainclubai.ae
##env_host = trinodev.alainclubai.ae
##env_port = 443
##env_username = admin
##env_password = Admin_123
##env_BASE_URL_SERVICE = https://devdigixt.alainclubai.ae
##catalog_name = raw
##user_name=admin
##user_password=admin
##env_BASE_URL_IDP = https://devdigixt.alainclubai.ae
##env_Client_NAME = datalake-client
##env_Login_URL = /auth/realms/Datalake/protocol/openid-connect/token
#
#################################################################################
#
########################ALAIN PROD DATA CONFIGURATION #############################
##trino_ui_host=https://trino-prod.digixt.ae
##env_host = trino-prod.digixt.ae
##env_port = 443
##env_username = admin
##env_password = Prod@2024
##env_BASE_URL_SERVICE = https://prod.digixt.ae
###catalog_name = tpchdatawarehouse
##catalog_name = datalake
##user_name=admin
##user_password=admin
##env_BASE_URL_IDP = https://prod.digixt.ae
##env_Client_NAME = datalake-client
##env_Login_URL = /auth/realms/Datalake/protocol/openid-connect/token
##catalogs_name = raw
#################################################################################
#
#
